DROP TABLE Manager cascade constraints;
DROP TABLE Farm cascade constraints;
DROP TABLE Employee cascade constraints;
DROP TABLE QualityCost cascade constraints;
DROP TABLE ExpertiseWage cascade constraints;
DROP TABLE PigStyCost cascade constraints;
DROP TABLE FodderType cascade constraints;
DROP TABLE Buys cascade constraints;
DROP TABLE PigSty cascade constraints;
DROP TABLE Veterinarian cascade constraints;
DROP TABLE Cleaner;
DROP TABLE Feeder;
DROP TABLE Feeds;
DROP TABLE Cleans;
DROP TABLE BreedFodder cascade constraints;
DROP TABLE PigStyMapping cascade constraints;
DROP TABLE PigPriceMapping cascade constraints;
DROP TABLE Pig cascade constraints;
DROP TABLE MedicalRecord cascade constraints;
DROP TABLE Creates cascade constraints;
commit;